# Generated by Django 5.0 on 2023-12-19 20:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0002_remove_book_created_remove_book_modified"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="created",
            field=models.DateField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="book", name="modified", field=models.DateField(auto_now=True),
        ),
    ]
