# Generated by Django 5.0 on 2023-12-20 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0003_book_created_book_modified"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="author",
            field=models.CharField(default="Adam Mickiewicz", max_length=100),
            preserve_default=False,
        ),
    ]
