# Generated by Django 5.0 on 2023-12-21 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0004_book_author"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="author",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
