# Generated by Django 5.0 on 2023-12-21 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0005_alter_book_author"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="file",
            field=models.ImageField(blank=True, upload_to="uploads"),
        ),
    ]
