# Generated by Django 5.0 on 2024-01-08 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0009_order_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="deliverymodel",
            name="country",
            field=models.CharField(max_length=15),
        ),
    ]
