# Generated by Django 5.0 on 2024-01-09 08:40

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0010_alter_deliverymodel_country"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(old_name="DeliveryModel", new_name="Address",),
    ]
