# Generated by Django 5.0 on 2024-01-10 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0012_useraddress_userprofile_useraddress_profile"),
    ]

    operations = [
        migrations.RemoveField(model_name="address", name="user",),
    ]
