# Generated by Django 5.1 on 2024-09-16 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0013_remove_address_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="Genres",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "genre",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("akcja", "Akcja"),
                            ("przygoda", "Przygoda"),
                            ("historia", "Historia"),
                            ("komedia", "Komedia"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="book",
            name="genres",
            field=models.ManyToManyField(to="myapp.genres"),
        ),
    ]
