# Generated by Django 5.1 on 2024-09-16 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0015_alter_genres_genre"),
    ]

    operations = [
        migrations.RenameField(model_name="genres", old_name="genre", new_name="name",),
    ]
