# Generated by Django 5.1 on 2024-09-16 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0016_rename_genre_genres_name"),
    ]

    operations = [
        migrations.RenameModel(old_name="Genres", new_name="Genre",),
    ]
