# Generated by Django 5.1 on 2024-09-16 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0017_rename_genres_genre"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="genres",
            field=models.ManyToManyField(blank=True, null=True, to="myapp.genre"),
        ),
        migrations.AlterField(
            model_name="genre",
            name="name",
            field=models.CharField(
                choices=[
                    ("akcja", "Akcja"),
                    ("przygoda", "Przygoda"),
                    ("historia", "Historia"),
                    ("komedia", "Komedia"),
                ],
                default="akcja",
                max_length=15,
            ),
        ),
    ]
