# Generated by Django 5.1 on 2024-09-16 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0018_alter_book_genres_alter_genre_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="genres",
            field=models.ManyToManyField(blank=True, to="myapp.genre"),
        ),
    ]
